In [19]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
#sentences
sent=['i love my dog',
      'i love my cat',
      'you love my dog!',
      'do you think my dog is amazing?',
      'my dog loves my manatee',
      'my cat loves my manatee',
      'cats and dogs are great pets',]

In [21]:
#define vocabulary size
voc_size=10000


In [22]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8809, 5718, 5625, 1680],
 [8809, 5718, 5625, 2101],
 [5853, 5718, 5625, 1680],
 [4230, 5853, 6064, 5625, 1680, 8812, 3549],
 [5625, 1680, 2158, 5625, 2914],
 [5625, 2101, 2158, 5625, 2914],
 [9595, 6444, 1985, 9976, 8303, 8999]]

In [38]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [43]:
sent_length=10
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0,    0,    0, 8809, 5718, 5625, 1680],
       [   0,    0,    0,    0,    0,    0, 8809, 5718, 5625, 2101],
       [   0,    0,    0,    0,    0,    0, 5853, 5718, 5625, 1680],
       [   0,    0,    0, 4230, 5853, 6064, 5625, 1680, 8812, 3549],
       [   0,    0,    0,    0,    0, 5625, 1680, 2158, 5625, 2914],
       [   0,    0,    0,    0,    0, 5625, 2101, 2158, 5625, 2914],
       [   0,    0,    0,    0, 9595, 6444, 1985, 9976, 8303, 8999]],
      dtype=int32)

In [44]:
#feature representation
dim=10


In [57]:
#create model AND compile

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


In [58]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step


array([[[-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.03051169,  0.01271905,  0.00497919, -0.0

In [47]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 8809, 5718, 5625, 1680],
      dtype=int32)

In [62]:
model.predict(embedded_docs[0:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step


array([[[-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.0038306 ,  0.01238846,  0.04363922,  0.03774679,
          0.04310494,  0.01983079, -0.03891361,  0.04162775,
         -0.02639061,  0.00941072],
        [-0.03051169,  0.01271905,  0.00497919, -0.0